apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ku7vcyp6r-go 
  janus-idp.io/tekton: ku7vcyp6r-go
  backstage.io/kubernetes-id: ku7vcyp6r-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ku7vcyp6r-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml