apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ku7vcyp6r-go
  janus-idp.io/tekton: ku7vcyp6r-go
  backstage.io/kubernetes-id: ku7vcyp6r-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ku7vcyp6r-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
